fix(rds): Clamp metric to 5-minutes period for DiskSpaceUsage
cdklabs/cdk-monitoring-constructs pull request #324
Opened 2023-02-09 15:19 UTC by edisongustavo

The `VolumeBytesUsed` metric has a minimum period of 5-minutes in my RDS clusters.

I didn't find this information documented in the AWS docs, but it gives hints for the other Volume* metrics here:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.AuroraMySQL.Monitoring.Metrics.html

At the monitoring of my RDS clusters I have changed to a 5-minute period, but I'd like to keep the 1-minute for the other metrics. We can discard this PR if you think this approach is not suitable.

---

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license_

2023-02-10 18:58 UTC, echeung-amzn requested changes

2023-02-10 18:58 UTC, echeung-amzn commented on lib/common/metric/MetricFactory.ts
> +    let resolvedPeriod =
You could declare this as a `const` and just `return reportFrequency` directly when clamping.

2023-02-10 18:58 UTC, echeung-amzn commented on lib/common/metric/MetricFactory.ts
> +  CLAMP_TO_MINIMUM_REPORT_FREQUENCY,
Can you add some docs to describe the behaviours a bit more?

That said, it seems safer to always error and force the implementer to be explicit with their intent on what the period should be.

2023-02-10 18:58 UTC, echeung-amzn commented on lib/monitoring/aws-rds/RdsClusterMetricFactory.ts
> +  metricFreeStorageInBytes(period?: Duration) {
Does this need to be clamped?

2023-02-10 18:58 UTC, echeung-amzn commented on lib/monitoring/aws-rds/RdsClusterMetricFactory.ts
> +  metricUsedStorageInBytes(period?: Duration) {
Would like to see a test covering new behaviour.

2023-02-13 14:44 UTC, edisongustavo commented
I agree with your points. I tried to refactor the code but I think the code is getting too confusing for too little gain.

The issue that I think is the problem is that this is creating a new entity which is composed of

- desired period
- minimum period supported by metric

Then we'd have the handling of mismatched periods where we could either:

1. Throw an error if user specified a period not compatible with the minimum supported by the metric
2. Clamp the value
3. Ignore the mismatch

I will park this idea for now and maybe come back to it later. In the meantime I'm just using 5-minute periods in my RDS dashboard. If you disagree and think this is valuable, I can get back to it.

2023-02-13 14:44 UTC, closed without merging